import { WhisperModel } from "@/types/transript"

export const whisperModels: { name: WhisperModel; disk: string; memory: string }[] = [
  { name: "tiny", disk: "75 MB", memory: "~390 MB" },
  { name: "tiny.en", disk: "75 MB", memory: "~390 MB" },
  { name: "base", disk: "142 MB", memory: "~500 MB" },
  { name: "base.en", disk: "142 MB", memory: "~500 MB" },
  { name: "small", disk: "466 MB", memory: "~1.0 GB" },
  { name: "small.en", disk: "466 MB", memory: "~1.0 GB" },
  { name: "medium", disk: "1.5 GB", memory: "~2.6 GB" },
  { name: "medium.en", disk: "1.5 GB", memory: "~2.6 GB" },
  { name: "large-v1", disk: "2.9 GB", memory: "~4.7 GB" },
  { name: "large", disk: "2.9 GB", memory: "~4.7 GB" },
  { name: "large-v3-turbo", disk: "1.5 GB", memory: "~2.6 GB" },
]

export const llmModels: { name: string; value: string; models: string[] }[] = [
  {
    name: "Google",
    value: "google",
    models: [
      "gemini-1.5-flash",
      "gemini-1.5-flash-latest",
      "gemini-1.5-flash-001",
      "gemini-1.5-flash-002",
      "gemini-1.5-flash-8b",
      "gemini-1.5-flash-8b-latest",
      "gemini-1.5-flash-8b-001",
      "gemini-1.5-pro",
      "gemini-1.5-pro-latest",
      "gemini-1.5-pro-001",
      "gemini-1.5-pro-002",
      "gemini-2.0-flash",
      "gemini-2.0-flash-001",
      "gemini-2.0-flash-live-001",
      "gemini-2.0-flash-lite",
      "gemini-2.0-pro-exp-02-05",
      "gemini-2.0-flash-thinking-exp-01-21",
      "gemini-2.0-flash-exp",
      "gemini-2.5-pro",
      "gemini-2.5-flash",
      "gemini-2.5-flash-lite",
      "gemini-2.5-flash-image-preview",
      "gemini-2.5-pro-exp-03-25",
      "gemini-2.5-flash-preview-04-17",
      "gemini-exp-1206",
      "gemma-3-12b-it",
      "gemma-3-27b-it",
    ],
  },
  {
    name: "Ollama",
    value: "ollama",
    models: ["llama3.2:3b", "mistral:7b", "llama2:13b", "qwen2.5:7b"],
  },
]
